name: library_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  datetime_picker_formfield_new: ^2.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_randomcolor: ^1.0.16
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  meta: ^1.15.0
  nav_service: ^0.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.jpg
  android_12:
    color: "#ffffff"
    image: assets/logo.jpg
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
